#ifndef BOOK_MANAGEMENT_GUARD__H 
#define BOOK_MANAGEMENT_GUARD__H
#include <stdio.h>
/*You can extend the structs (Book and BookArray) defined in this head file;
  However, you may not change the function prototypes. 
  You are also free to add additional head files and data structures as needed. 
*/


typedef struct _Book {
	     int id; //Book ID
		 char *title; //book title
		 char *authors; //comma separated list of authors
		 int year; // year of publication
		 int copies; //number of copies the library has
}Book;

typedef struct _BookArray {
	 struct _BookArray* next; // pointer to array (or linked list) of struct Book.
	 struct _BookArray* pnext;
	 struct _BookArray* bnext;
	 unsigned int length; // number of elements in the (Book*) array 
	 Book book;//the books that will be added.
}BookArray;

void Displaybook(BookArray *headnode);
void ShowFindbook(BookArray *head);
void ShowBorrowbook(BookArray *head); 
void Searchbook(BookArray *headnode);
void Search_title(BookArray *headnode);
void Search_author(BookArray *headnode);
void Search_year(BookArray *headnode);
BookArray *createheadnode();
BookArray *createnode(Book books);
BookArray *find_book_by_id (unsigned int id,BookArray *head);
//saves the database of books in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_books(BookArray *headnode);

	
//loads the database of books from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_books(BookArray* headNode);

//adds a book to the ones available to the library
//returns 0 if the book could be added, or an error code otherwise
//int add_book(Book book,	BookArray *head);
int  add_book(Book book,BookArray *headnode2);

//removes a book from the library
//returns 0 if the book could be successfully removed, or an error code otherwise.
int remove_book(Book book,BookArray *head);

//finds books with a given title.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the 
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
BookArray *find_book_by_title (const char *title,BookArray *head);

//finds books with the given authors.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the 
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
BookArray *find_book_by_author (const char *author,BookArray *head);

//finds books published in the given year.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the 
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
BookArray *find_book_by_year (unsigned int year,BookArray *head);


#endif
